### ISSUE TITLE
Restricted access to original processed folder

### ISSUE THREAD

**Issue by tengann** [JhaKanchan15/PPI_GNN#1]
I would like to replicate results mentioned in the paper. However, access to the original processed folder containing all 4,188 protein graphs is restricted and will require permission. I would greatly appreciate if you can assist and grant me access to the folder. Thank you very much.

**Comment by XueWang2019** [comment]
I also would like to replicate the results. Could you pls help with it? Thanks in advance.

**Comment by Soma100** [comment]
I also would like to replicate the results. Could you pls help with it? Thanks in advance.
